apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: d29yZHByZXNz
  MYSQL_USER: d3AtYWRtaW4=
  MYSQL_PASSWORD: YWRtaW4=
